name: End-to-end Tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    # environment: qa
    steps:
      - name: 📁 Copiando o Projeto 📂 
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests

      - name: 🧪 Rodando os Testes do Cypress 🧪
        uses: cypress-io/github-action@v6

      - name: ⛔ Upload dos arquivos em caso de falha 🎬
        # after the test run completes store videos and any screenshots
        uses: actions/upload-artifact@v4
        # add the line below to store screenshots only on failures
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore 
        # 'warn' or 'error' are also available, defaults to `warn`
      - name: ✅ Upload dos arquivos em caso de sucesso 📹
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
          